;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		apply-operation-to-number-at-point
		backward-sexp
		comment-or-uncomment-region
		consult-line
		consult-yank-pop
		copilot-accept-completion
		crux-kill-line-backwards
		crux-move-beginning-of-line
		crux-smart-kill-line
		cycle-spacing
		electric-newline-and-maybe-indent
		electric-pair-delete-pair
		end-of-visual-line
		forward-sexp
		indent-for-tab-command
		isearch-abort
		iy-go-to-char--command
		iy-go-to-char-quit
		jump-char-forward
		jump-char-process-char
		kill-region
		markdown-outdent-or-delete
		mc--insert-letter-and-increase
		mc--insert-number-and-increase
		org-cycle
		org-delete-char
		org-end-of-line
		org-return-and-maybe-indent
		org-self-insert-command
		org-shiftleft
		org-yank
		overwrite-mode
		search-forward
		sgml-slash
		transpose-words
		wdired--self-insert
		zop-up-to-char
		))

(setq mc/cmds-to-run-once
      '(
		avy-goto-char
		avy-goto-word-1
		cider-load-buffer
		corfu-next
		dcl-electric-character
		handle-switch-frame
		lsp-signature-stop
		lsp-ui-doc--handle-mouse-movement
		mouse-set-region
		mouse-yank-primary
		picture-self-insert
		pixel-scroll-precision
		pixel-scroll-start-momentum
		winum-select-window-2
		winum-select-window-3
		))
