Personal work-in-progress Emacs 29+ IDE setup aimed to be on par with NeoVim and VSCode. Mainly focused for coding Clojure, PHP and Python.

This is not a stable project for public consumption at this point.

Upstream Bedrock project or some other config distribution is probably a better starting point for a new config for most people.

* Supported IDE features by language

| Language | LSP | DAP | Tree-sitter | TS "auto build" |
|----------+-----+-----+-------------+-----------------|
| PHP      | x   | x   | x*          |                 |
| Python   | x   | x*  |             | x               |
| Clojure  | x   | **  |             | x               |
| Yaml     | x   |     | x           | x               |

- * PHP tree-sitter needs to be improved to support embedded HTML and PHP eg. mixed documents. Related pull request https://github.com/nvim-treesitter/nvim-treesitter/pull/5876 issue which has been updated since I looked at it the last time.
- ** Python DAP is enabled but not tested
- *** Clojure uses Cider which provides step debugger
  
* Background

Previously I have been coding mostly with VSCode instead of Emacs where it used to seem too complex to support different programming language specific features with various 3rd party packages for syntax coloring, indendation, code intelligence and debugging tools etc. Situation however changed last few years with tree-sitter, LSP and DAP projects where those features are being developed in editor-agnostic way and can be used and configured in more generic way on editor side.

* Details

This is based on my earlier Emacs Prelude based config that was mostly in use for simple scripting, magit and note taking that was migrated 2023 over to more minimal [[https://sr.ht/~ashton314/emacs-bedrock/][Bedrock starter config]], and is currently kept up to date with it's upstream development while deviating a bit in some parts. 

On original Bedrock config side, there are two files of interest: =early-init.el= and =init.el=. Follow [original repo readme](https://sr.ht/~ashton314/emacs-bedrock/) for more info. Using standard =use-package= (and with =straight=) for managing and configuring packages.

Own modifications and stuff imported from Prelude live under =personal/=.

- Includes many best parts of [[https://github.com/bbatsov/prelude][Emacs Prelude]] via [[https://github.com/bbatsov/crux][crux.el]] in =personal/custom.el= and programming config in =personal/programming.el=.
- Multiple cursors.
- Etc.

* Installation

Install Emacs 29+, from eg. [[https://packages.debian.org/bookworm-backports/emacs][Debian 12 Backports repo]] or [[https://github.com/d12frosted/homebrew-emacs-plus][d12frosted/homebrew-emacs-plus]] on Mac. Clone repo as =.emacs.d= and install tree-sitter grammars before start.

Also, Emacs 29.1 added the handy =--init-directory= flag. This means that you can run =emacs --init-directory path/to/emacs-bedrock/= and all the customizations and package installations will be isolated to the project directory. 

There may be some problems to diagnose after install, this is not a stable project after all.

** Tree-sitter grammars

Currently may fail to start if tree-sitter grammars are not in place at =~/.emacs.d/tree-sitter/=.

Install tree-sitter language grammars:

```
git clone https://github.com/casouri/tree-sitter-module.git
cd tree-sitter-module
./batch
mkdir ~/.emacs.d/tree-sitter
mv dist/* ~/.emacs.d/tree-sitter

```

Ref: https://git.savannah.gnu.org/cgit/emacs.git/tree/admin/notes/tree-sitter/starter-guide?h=feature/tree-sitter


PHP tree-sitter mode is more in progress and is built individually:

```
git clone https://github.com/tree-sitter/tree-sitter-php.git
cd tree-sitter-php
make
cp libtree-sitter-php.dylib ~/.emacs.d/tree-sitter
```

** LSP
Uses lsp-mode over eglot which installs LSP servers automatically.

** Copilot
=M-x copilot-login=
